import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Cards from '../components/cards/cards'
import Nav from '../components/cards/nav'
import Boxs from '../components/cards/boxs'
import Creatissue from '../components/cards/creatissue'
import Issue from '../components/cards/issue'
// import LoginForm from '../components/loginForm'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet"></link>
      </Head>
            <Nav></Nav>
            <Cards></Cards>
            <Boxs></Boxs>
            <Issue></Issue>
            <Creatissue></Creatissue>
         </div>
  )
}
